name: Auto Build & Sync Astro News

on:
  push:
    paths:
      - 'auto_astro/src/content/news/**'

jobs:
  build-sync-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build Astro
        run: |
          cd auto_astro
          npm ci
          npm run build
          cp -r dist/news ../_build/html/

      - name: Commit and push HTML news
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _build/html/news/
          git commit -m "🛰️ Auto build Astro News from .md content"
          git push